# Generated by Django 2.1.1 on 2018-09-25 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qnaquestion',
            old_name='perent',
            new_name='parent',
        ),
    ]
