# Generated by Django 2.1.1 on 2018-10-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livesession', '__first__'),
        ('blogs', '0002_qnaquestion_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='qnaquestion',
            name='is_live_question',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qnaquestion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='livesession.LiveQuestionSession'),
        ),
    ]
