# Generated by Django 2.1.1 on 2018-09-25 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180925_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pin_board',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shared.CoursePinBoard'),
        ),
    ]
