# Generated by Django 2.1.1 on 2018-10-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveQuestionSession',
            fields=[
                ('content_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shared.Content')),
                ('title', models.CharField(max_length=150)),
                ('begin_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
            bases=('shared.content',),
        ),
    ]
